### ISSUE TITLE
What's execute this code?

### ISSUE THREAD

**Issue by bjrambo** [xlanor/matilda-tools#2]
https://github.com/xlanor/matilda-tools/blob/f5e71baca7401691eab65b587365a19581ff3606/newstories_mothership.php#L19
```php
$html = $obj['html'];
$results = print_r($obj['html'],true);
$x = new DOMDocument;
$x->loadHTML($results);
```
change
```php
$x = new DOMDocument;
$x->loadHTML(print_r($obj['html'],true));
```
if the variable is declared once there is no need to re-declare.
And, `$html` is not use.

so you can use the it change code.

**Comment by bjrambo** [comment]
#3 clean up code.

**Comment by xlanor** [comment]
Merged, thanks alot :)

I think that was from when I was trying different things, I forgot to take it out
